// DashboardViewModel with GetX
// Generated by Mason
import 'package:get/get.dart';
import '../services/dashboard_service.dart';

class DashboardViewModel extends GetxController {
  final DashboardService _service = DashboardService();
  
  final RxBool isLoading = false.obs;
  final Rx<String?> errorMessage = Rx<String?>(null);
  final RxList<dynamic> items = <dynamic>[].obs;
  
  @override
  void onInit() {
    super.onInit();
    fetchData();
  }
  
  Future<void> fetchData() async {
    isLoading.value = true;
    errorMessage.value = null;
    
    try {
      // TODO: Implement data fetching
      // Example: final result = await _service.getItems();
      // items.value = result;
    } catch (e) {
      errorMessage.value = e.toString();
    } finally {
      isLoading.value = false;
    }
  }
}
