// AnalyticsService
// This file was auto-generated by Mason

class AnalyticsService {
  // TODO: Add service methods and properties
  
  Future<void> initialize() async {
    // TODO: Implement initialization logic
  }
}
